New variable card button
concord-consortium/quantity-playground pull request #38
Opened 2022-11-22 19:45 UTC by tealefristoe

This PR makes some small changes to allow the CLUE tile toolbar new variable card button to work properly.
- Allows the built in new card button to be hidden by a client
- Allows a client to specify the diagram refs so it can position cards properly.

2022-11-28 19:07 UTC, scytacki requested changes
This looks good. I'm just hoping we can come up with a way to support the node positioning without exposing the react flow instance.

2022-11-28 19:49 UTC, tealefristoe commented on src/diagram/components/diagram.tsx
> +  externalSetRfInstance?: (val: any) => void;
It's used for `project` as well as the zoom functions. I'll see if I can figure out an alternative.

Do you think it's ok to keep the external react flow wrapper? It's only used for `getBoundingClientRect`.

2022-11-30 01:41 UTC, scytacki approved these changes
Seems good to me.

I don't think it needs to be an MST model it could just be a plain object. But we can change that later.

2022-11-30 16:45 UTC, emcelroy approved these changes
Looks good to me 👍

2022-11-30 20:26 UTC, merged